name: "Github CI Bot"
description: "Have a CI Bot automatically do things for you"
author: "wzshiming"

runs:
  using: "composite"
  steps:
    - run: cd ${{ github.action_path }} && go run .
      shell: bash